version: "2"
services:
  stats-db:
    image: postgres
  stats-web:
    image: wolfskaempf/statistics
    ports:
      - "80:8000"
    volumes:
      - ./media/:/srv/statistics/media/
    depends_on:
      - "stats-db"
