# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 16:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticscore', '0024_session_session_gender_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_picture',
            field=models.ImageField(upload_to=b'session_pictures/'),
        ),
    ]
