# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 19:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticscore', '0028_auto_20160211_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[(b'IS', b'International Session'), (b'IF', b'International Forum'), (b'NS', b'National Session'), (b'RS', b'Regional Session'), (b'SS', b'Small Scale Session'), (b'OE', b'Other Event')], default=b'RS', max_length=5),
        ),
    ]
