# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticscore', '0041_auto_20180117_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historictopicplace',
            old_name='historic_time',
            new_name='historic_date',
        ),
    ]
