# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-18 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [(b'statistics', '0001_initial'), (b'statistics', '0002_auto_20150810_1524'), (b'statistics', '0003_session_session_statistics'), (b'statistics', '0003_auto_20150814_1411'), (b'statistics', '0004_merge'), (b'statistics', '0005_contentpoint_point_type'), (b'statistics', '0006_auto_20150816_2359'), (b'statistics', '0007_auto_20150817_0000'), (b'statistics', '0008_session_session_email'), (b'statistics', '0009_session_session_color'), (b'statistics', '0010_session_session_is_visible'), (b'statistics', '0011_auto_20150820_1639'), (b'statistics', '0012_auto_20150822_1237'), (b'statistics', '0013_auto_20150823_1908'), (b'statistics', '0014_auto_20150823_1909'), (b'statistics', '0015_session_session_has_technical_problems'), (b'statistics', '0013_auto_20150822_1653'), (b'statistics', '0015_merge'), (b'statistics', '0016_merge'), (b'statistics', '0017_auto_20150825_0026'), (b'statistics', '0018_committee_next_subtopics'), (b'statistics', '0019_runningorder'), (b'statistics', '0020_auto_20150925_1646'), (b'statistics', '0021_auto_20150925_1648'), (b'statistics', '0022_gender'), (b'statistics', '0023_gender_timestamp'), (b'statistics', '0024_session_session_gender_enabled'), (b'statistics', '0025_auto_20160202_1742'), (b'statistics', '0026_auto_20160202_2345'), (b'statistics', '0027_auto_20160207_2201'), (b'statistics', '0028_auto_20160211_1628'), (b'statistics', '0029_session_session_type'), (b'statistics', '0030_auto_20161223_1754'), (b'statistics', '0031_announcement'), (b'statistics', '0032_announcement_announcement_type'), (b'statistics', '0033_auto_20170225_0033'), (b'statistics', '0034_remove_session_session_color'), (b'statistics', '0035_rename_sessions'), (b'statistics', '0036_auto_20171223_1209')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDebate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_debate', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_round', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_name', models.CharField(max_length=7)),
                ('committee_topic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('active_debate', models.CharField(blank=True, max_length=7, null=True)),
                ('active_round', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('point_type', models.CharField(choices=[(b'P', b'Point'), (b'DR', b'Direct Response')], default=b'P', max_length=2)),
                ('committee_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Committee')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
                ('session_description', models.CharField(max_length=200)),
                ('session_picture', models.URLField()),
                ('session_country', models.CharField(choices=[(b'AL', b'Albania'), (b'AM', b'Armenia'), (b'AT', b'Austria'), (b'AZ', b'Azerbaijan'), (b'BY', b'Belarus'), (b'BE', b'Belgium'), (b'BA', b'Bosnia and Herzegovina'), (b'HR', b'Croatia'), (b'CY', b'Cyprus'), (b'CZ', b'Czech Republic'), (b'DK', b'Denmark'), (b'EE', b'Estonia'), (b'FI', b'Finland'), (b'FR', b'France'), (b'GE', b'Georgia'), (b'DE', b'Germany'), (b'GR', b'Greece'), (b'HU', b'Hungary'), (b'IE', b'Ireland'), (b'IT', b'Italy'), (b'XK', b'Kosovo'), (b'LV', b'Latvia'), (b'LT', b'Lithuania'), (b'LU', b'Luxembourg'), (b'NL', b'The Netherlands'), (b'NO', b'Norway'), (b'PL', b'Poland'), (b'PT', b'Portugal'), (b'RO', b'Romania'), (b'RU', b'Russia'), (b'RS', b'Serbia'), (b'SI', b'Slovenia'), (b'ES', b'Spain'), (b'SE', b'Sweden'), (b'CH', b'Swizerland'), (b'TR', b'Turkey'), (b'UA', b'Ukraine'), (b'GB', b'The United Kingdom')], default=b'AL', max_length=2)),
                ('session_start_date', models.DateTimeField(verbose_name=b'start date')),
                ('session_end_date', models.DateTimeField(verbose_name=b'end date')),
                ('session_rounds_enabled', models.BooleanField(default=True, verbose_name=b'debate rounds enabled')),
                ('session_subtopics_enabled', models.BooleanField(default=True, verbose_name=b'committee subtopics enabled')),
                ('session_voting_enabled', models.BooleanField(default=True, verbose_name=b'session-wide voting enabled')),
                ('session_max_rounds', models.PositiveSmallIntegerField(default=3)),
                ('session_admin_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_admin', to=settings.AUTH_USER_MODEL)),
                ('session_submission_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_submit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statistics.Committee')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statistics.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, default=django.utils.timezone.now)),
                ('active_debate', models.CharField(max_length=8)),
                ('in_favour', models.PositiveSmallIntegerField()),
                ('against', models.PositiveSmallIntegerField()),
                ('abstentions', models.PositiveSmallIntegerField()),
                ('absent', models.PositiveSmallIntegerField()),
                ('committee_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Committee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Session')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Session'),
        ),
        migrations.AddField(
            model_name='point',
            name='subtopics',
            field=models.ManyToManyField(blank=True, to=b'statistics.SubTopic'),
        ),
        migrations.AddField(
            model_name='committee',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Session'),
        ),
        migrations.AddField(
            model_name='activeround',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Session'),
        ),
        migrations.AddField(
            model_name='activedebate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Session'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='committee_name',
            field=models.CharField(max_length=8),
        ),
        migrations.AddField(
            model_name='session',
            name='session_statistics',
            field=models.CharField(choices=[(b'S', b'Statistics Only'), (b'C', b'Point Content Only'), (b'JF', b'Single Form Statistics'), (b'SF', b'Split Form Statistics'), (b'N/A', b'No Statistics (Only Voting)')], default=b'SF', max_length=3),
        ),
        migrations.CreateModel(
            name='ContentPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_debate', models.CharField(max_length=8)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('point_content', models.TextField()),
                ('committee_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Committee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Session')),
                ('point_type', models.CharField(choices=[(b'P', b'Point'), (b'DR', b'Direct Response')], default=b'P', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='point',
            name='active_debate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_statistics',
            field=models.CharField(choices=[(b'S', b'Statistics Only'), (b'C', b'Point Content Only'), (b'JF', b'Single Form Statistics'), (b'SF', b'Split Form Statistics'), (b'N/A', b'No Statistics (Only Voting)')], default=b'JF', max_length=3),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_statistics',
            field=models.CharField(choices=[(b'S', b'Statistics Only'), (b'C', b'Point Content Only'), (b'JF', b'Joint Form Statistics'), (b'SF', b'Split Form Statistics'), (b'N/A', b'No Statistics (Only Voting)')], default=b'JF', max_length=3),
        ),
        migrations.AddField(
            model_name='session',
            name='session_email',
            field=models.EmailField(default='oliver@stenbom.eu', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='session_color',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='session_is_visible',
            field=models.BooleanField(default=True, verbose_name=b'is visible'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activedebate',
            name='active_debate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_resolution_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_twitter_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_website_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_has_technical_problems',
            field=models.BooleanField(default=False, verbose_name=b'session has technical problems'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_submission_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_submit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='committee',
            name='next_subtopics',
            field=models.ManyToManyField(blank=True, related_name='next_subtopics+', to=b'statistics.SubTopic'),
        ),
        migrations.CreateModel(
            name='RunningOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('point_type', models.CharField(choices=[(b'P', b'Point'), (b'DR', b'Direct Response')], default=b'P', max_length=2)),
                ('committee_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Committee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Session')),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='session_statistics',
            field=models.CharField(choices=[(b'S', b'Statistics Only'), (b'C', b'Point Content Only'), (b'JF', b'Joint Form Statistics'), (b'SF', b'Split Form Statistics'), (b'R', b'Running Order Statistics'), (b'RC', b'Running Order Statistics with Point Content')], default=b'JF', max_length=3),
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_rounds_enabled',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_subtopics_enabled',
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(b'F', b'Female'), (b'M', b'Male'), (b'O', b'Other')], default=b'F', max_length=1)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Committee')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='gender_enabled',
            field=models.BooleanField(default=False, verbose_name=b'gender statistics enabled'),
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_picture',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='session',
            name='picture',
            field=models.ImageField(upload_to=b'session_pictures/'),
        ),
        migrations.AddField(
            model_name='session',
            name='gender_number_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='gender_number_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='gender_number_other',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_country',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='session',
            name='country',
            field=models.CharField(choices=[(b'AL', b'Albania'), (b'AM', b'Armenia'), (b'AT', b'Austria'), (b'AZ', b'Azerbaijan'), (b'BY', b'Belarus'), (b'BE', b'Belgium'), (b'BA', b'Bosnia and Herzegovina'), (b'HR', b'Croatia'), (b'CY', b'Cyprus'), (b'CZ', b'Czech Republic'), (b'DK', b'Denmark'), (b'EE', b'Estonia'), (b'FI', b'Finland'), (b'FR', b'France'), (b'GE', b'Georgia'), (b'DE', b'Germany'), (b'GR', b'Greece'), (b'HU', b'Hungary'), (b'IE', b'Ireland'), (b'IT', b'Italy'), (b'XK', b'Kosovo'), (b'LV', b'Latvia'), (b'LT', b'Lithuania'), (b'LU', b'Luxembourg'), (b'NL', b'The Netherlands'), (b'NO', b'Norway'), (b'PL', b'Poland'), (b'PT', b'Portugal'), (b'RO', b'Romania'), (b'RU', b'Russia'), (b'RS', b'Serbia'), (b'SI', b'Slovenia'), (b'ES', b'Spain'), (b'SE', b'Sweden'), (b'CH', b'Switzerland'), (b'TR', b'Turkey'), (b'UA', b'Ukraine'), (b'GB', b'The United Kingdom')], default=b'AL', max_length=2),
        ),
        migrations.AlterField(
            model_name='session',
            name='country',
            field=models.CharField(choices=[(b'AL', b'Albania'), (b'AM', b'Armenia'), (b'AT', b'Austria'), (b'AZ', b'Azerbaijan'), (b'BY', b'Belarus'), (b'BE', b'Belgium'), (b'BA', b'Bosnia and Herzegovina'), (b'HR', b'Croatia'), (b'CY', b'Cyprus'), (b'CZ', b'Czech Republic'), (b'EE', b'Estonia'), (b'FI', b'Finland'), (b'FR', b'France'), (b'GE', b'Georgia'), (b'DE', b'Germany'), (b'GR', b'Greece'), (b'HU', b'Hungary'), (b'IE', b'Ireland'), (b'IT', b'Italy'), (b'XK', b'Kosovo'), (b'LV', b'Latvia'), (b'LT', b'Lithuania'), (b'LU', b'Luxembourg'), (b'NL', b'The Netherlands'), (b'NO', b'Norway'), (b'PL', b'Poland'), (b'PT', b'Portugal'), (b'RO', b'Romania'), (b'RU', b'Russia'), (b'RS', b'Serbia'), (b'SI', b'Slovenia'), (b'SK', b'Slovakia'), (b'ES', b'Spain'), (b'SE', b'Sweden'), (b'CH', b'Switzerland'), (b'TR', b'Turkey'), (b'UA', b'Ukraine'), (b'GB', b'The United Kingdom')], default=b'AL', max_length=2),
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[(b'IS', b'International Session'), (b'IF', b'International Forum'), (b'NS', b'National Session'), (b'RS', b'Regional Session'), (b'SS', b'Small Scale Session'), (b'OE', b'Other Event')], default=b'RS', max_length=3),
        ),
        migrations.AddField(
            model_name='session',
            name='picture_author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='picture_author_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='picture_licence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='picture_license_link',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateTimeField()),
                ('announcement_type', models.CharField(choices=[(b'alert-success', b'Success'), (b'alert-info', b'Info'), (b'alert-warning', b'Warning'), (b'alert-danger', b'Danger')], default=b'alert-info', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_color',
        ),
        migrations.RenameField(
            model_name='committee',
            old_name='committee_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='committee',
            old_name='committee_topic',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_admin_user',
            new_name='admin_user',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_facebook_link',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_has_technical_problems',
            new_name='has_technical_problems',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_is_visible',
            new_name='is_visible',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_max_rounds',
            new_name='max_rounds',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_resolution_link',
            new_name='resolution_link',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_submission_user',
            new_name='submission_user',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_twitter_link',
            new_name='twitter_link',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_voting_enabled',
            new_name='voting_enabled',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_website_link',
            new_name='website_link',
        ),
    ]
