# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 12:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0023_gender_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_gender_enabled',
            field=models.BooleanField(default=False, verbose_name=b'gender statistics enabled'),
        ),
    ]
