# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0025_auto_20160202_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='gender_number_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='gender_number_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='gender_number_other',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
