# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0026_auto_20160202_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_country',
            field=models.CharField(choices=[(b'AL', b'Albania'), (b'AM', b'Armenia'), (b'AT', b'Austria'), (b'AZ', b'Azerbaijan'), (b'BY', b'Belarus'), (b'BE', b'Belgium'), (b'BA', b'Bosnia and Herzegovina'), (b'HR', b'Croatia'), (b'CY', b'Cyprus'), (b'CZ', b'Czech Republic'), (b'DK', b'Denmark'), (b'EE', b'Estonia'), (b'FI', b'Finland'), (b'FR', b'France'), (b'GE', b'Georgia'), (b'DE', b'Germany'), (b'GR', b'Greece'), (b'HU', b'Hungary'), (b'IE', b'Ireland'), (b'IT', b'Italy'), (b'XK', b'Kosovo'), (b'LV', b'Latvia'), (b'LT', b'Lithuania'), (b'LU', b'Luxembourg'), (b'NL', b'The Netherlands'), (b'NO', b'Norway'), (b'PL', b'Poland'), (b'PT', b'Portugal'), (b'RO', b'Romania'), (b'RU', b'Russia'), (b'RS', b'Serbia'), (b'SI', b'Slovenia'), (b'ES', b'Spain'), (b'SE', b'Sweden'), (b'CH', b'Switzerland'), (b'TR', b'Turkey'), (b'UA', b'Ukraine'), (b'GB', b'The United Kingdom')], default=b'AL', max_length=2),
        ),
    ]
