# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-23 16:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticscore', '0029_session_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_picture_author',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='session',
            name='session_picture_author_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_picture_license',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='session',
            name='session_picture_license_link',
            field=models.URLField(blank=True),
        ),
    ]
