# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0030_auto_20161223_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_content', models.TextField()),
                ('announcement_timestamp', models.DateTimeField(auto_now=True)),
                ('announcement_valid_until', models.DateTimeField()),
            ],
        ),
    ]
