# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-23 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0035_rename_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='picture_author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='picture_licence',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
