# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticscore', '0036_auto_20171223_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committee',
            old_name='topic',
            new_name='topic_text',
        ),
    ]
