# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0037_topic_to_topic_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('type', models.CharField(blank=True, choices=[(b'CR', b'Creative'), (b'CF', b'Conflict'), (b'ST', b'Strategy')], max_length=2, null=True)),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricTopicPlace',
            fields=[
                ('topicplace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistics.TopicPlace')),
                ('historic_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('historic_country', models.CharField(blank=True, choices=[(b'AL', b'Albania'), (b'AM', b'Armenia'), (b'AT', b'Austria'), (b'AZ', b'Azerbaijan'), (b'BY', b'Belarus'), (b'BE', b'Belgium'), (b'BA', b'Bosnia and Herzegovina'), (b'HR', b'Croatia'), (b'CY', b'Cyprus'), (b'CZ', b'Czech Republic'), (b'EE', b'Estonia'), (b'FI', b'Finland'), (b'FR', b'France'), (b'GE', b'Georgia'), (b'DE', b'Germany'), (b'GR', b'Greece'), (b'HU', b'Hungary'), (b'IE', b'Ireland'), (b'IT', b'Italy'), (b'XK', b'Kosovo'), (b'LV', b'Latvia'), (b'LT', b'Lithuania'), (b'LU', b'Luxembourg'), (b'NL', b'The Netherlands'), (b'NO', b'Norway'), (b'PL', b'Poland'), (b'PT', b'Portugal'), (b'RO', b'Romania'), (b'RU', b'Russia'), (b'RS', b'Serbia'), (b'SI', b'Slovenia'), (b'SK', b'Slovakia'), (b'ES', b'Spain'), (b'SE', b'Sweden'), (b'CH', b'Switzerland'), (b'TR', b'Turkey'), (b'UA', b'Ukraine'), (b'GB', b'The United Kingdom')], max_length=2, null=True)),
                ('historic_session_type', models.CharField(blank=True, choices=[(b'IS', b'International Session'), (b'IF', b'International Forum'), (b'NS', b'National Session'), (b'RS', b'Regional Session'), (b'SS', b'Small Scale Session'), (b'OE', b'Other Event')], max_length=3, null=True)),
                ('historic_committee_name', models.CharField(max_length=8)),
            ],
            bases=('statistics.topicplace',),
        ),
        migrations.CreateModel(
            name='StatisticsTopicPlace',
            fields=[
                ('topicplace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistics.TopicPlace')),
                ('committee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistics.Committee')),
            ],
            bases=('statistics.topicplace',),
        ),
        migrations.AddField(
            model_name='topicplace',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Topic'),
        ),
    ]
