# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0037_auto_20171223_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('time_extra', models.DateTimeField(auto_now_add=True, null=True)),
                ('country_extra', models.CharField(blank=True, choices=[(b'AL', b'Albania'), (b'AM', b'Armenia'), (b'AT', b'Austria'), (b'AZ', b'Azerbaijan'), (b'BY', b'Belarus'), (b'BE', b'Belgium'), (b'BA', b'Bosnia and Herzegovina'), (b'HR', b'Croatia'), (b'CY', b'Cyprus'), (b'CZ', b'Czech Republic'), (b'EE', b'Estonia'), (b'FI', b'Finland'), (b'FR', b'France'), (b'GE', b'Georgia'), (b'DE', b'Germany'), (b'GR', b'Greece'), (b'HU', b'Hungary'), (b'IE', b'Ireland'), (b'IT', b'Italy'), (b'XK', b'Kosovo'), (b'LV', b'Latvia'), (b'LT', b'Lithuania'), (b'LU', b'Luxembourg'), (b'NL', b'The Netherlands'), (b'NO', b'Norway'), (b'PL', b'Poland'), (b'PT', b'Portugal'), (b'RO', b'Romania'), (b'RU', b'Russia'), (b'RS', b'Serbia'), (b'SI', b'Slovenia'), (b'SK', b'Slovakia'), (b'ES', b'Spain'), (b'SE', b'Sweden'), (b'CH', b'Switzerland'), (b'TR', b'Turkey'), (b'UA', b'Ukraine'), (b'GB', b'The United Kingdom')], max_length=2, null=True)),
                ('session_type_extra', models.CharField(blank=True, choices=[(b'IS', b'International Session'), (b'IF', b'International Forum'), (b'NS', b'National Session'), (b'RS', b'Regional Session'), (b'SS', b'Small Scale Session'), (b'OE', b'Other Event')], max_length=3, null=True)),
                ('committee_name_extra', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statistics.Topic'),
        ),
    ]
