# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-23 12:42
from __future__ import unicode_literals

from django.db import migrations


def save_topics(apps, schema_editor):
    Committee = apps.get_model('statistics', 'Committee')
    Topic = apps.get_model('statistics', 'Topic')
    for committee in Committee.objects.all():
        topic_text = committee.topic_text
        topic = Topic(text=topic_text)
        topic.save()
        committee.topic = topic


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0038_topics'),
    ]

    operations = [
        migrations.RunPython(save_topics)
    ]
