# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-23 12:42
from __future__ import unicode_literals

from django.db import migrations


def save_topics(apps, schema_editor):
    Committee = apps.get_model('statistics', 'Committee')
    StatisticsTopic = apps.get_model('statistics', 'StatisticsTopic')
    for committee in Committee.objects.all():
        topic_text = committee.topic_text
        existing_topics = StatisticsTopic.objects.all().filter(text=topic_text)
        if len(existing_topics):
            topic = existing_topics[0]
        else:
            topic = StatisticsTopic(text=topic_text)
            topic.save()
        committee.topic = topic
        committee.save()


def reverse_topic_saves(apps, schema_editor):
    StatisticsTopic = apps.get_model('statistics', 'StatisticsTopic')
    StatisticsTopic.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0038_topics'),
    ]

    operations = [
        migrations.RunPython(save_topics, reverse_topic_saves)
    ]
