# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0039_topics_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='difficulty',
            field=models.CharField(blank=True, choices=[(b'E', b'Easy'), (b'I', b'Intermediate'), (b'H', b'Hard')], max_length=1, null=True),
        ),
    ]
