# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticscore', '0040_topic_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historictopicplace',
            name='historic_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
