# Generated by Django 2.0.1 on 2018-02-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0042_auto_20180117_1526'),
        ('statistics', '0038_auto_20180124_2103'),
    ]

    operations = [
    ]
